name = "Particles"
uuid = "dbb53eb6-f4e4-11e9-1aca-071dd871ed0a"
license = "MIT"
desc = "Particle method to solve 1D conservation laws"
authors = ["Federico Stra <stra.federico@gmail.com>"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[compat]
DocStringExtensions = "0.8"
Plots = "1.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
