name = "ConservationLawsParticles"
uuid = "dbb53eb6-f4e4-11e9-1aca-071dd871ed0a"
license = "MIT"
desc = "Particle methods to solve 1D conservation laws"
authors = ["Federico Stra <stra.federico@gmail.com>"]
version = "0.8.4"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9"
RecipesBase = "1"
RecursiveArrayTools = "2, 3"
SafeTestsets = "0.1"
SpecialFunctions = "2"
Test = "1"
TestSetExtensions = "2, 3"
julia = "1.4"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Aqua", "SafeTestsets", "Test", "TestSetExtensions"]
